[build]
  command = "CI= npm run build"
  publish = "/dist"
  base = "/"
  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  